# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from rpc.payment.v1 import payment_pb2 as rpc_dot_payment_dot_v1_dot_payment__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rpc/payment/v1/payment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PaymentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePayment = channel.unary_unary(
                '/payment.v1.PaymentService/CreatePayment',
                request_serializer=rpc_dot_payment_dot_v1_dot_payment__pb2.CreatePaymentRequest.SerializeToString,
                response_deserializer=rpc_dot_payment_dot_v1_dot_payment__pb2.CreatePaymentResponse.FromString,
                _registered_method=True)
        self.GetPayment = channel.unary_unary(
                '/payment.v1.PaymentService/GetPayment',
                request_serializer=rpc_dot_payment_dot_v1_dot_payment__pb2.GetPaymentRequest.SerializeToString,
                response_deserializer=rpc_dot_payment_dot_v1_dot_payment__pb2.GetPaymentResponse.FromString,
                _registered_method=True)
        self.ProcessPaymentCallback = channel.unary_unary(
                '/payment.v1.PaymentService/ProcessPaymentCallback',
                request_serializer=rpc_dot_payment_dot_v1_dot_payment__pb2.ProcessPaymentCallbackRequest.SerializeToString,
                response_deserializer=rpc_dot_payment_dot_v1_dot_payment__pb2.ProcessPaymentCallbackResponse.FromString,
                _registered_method=True)
        self.CalculateWorkerIncome = channel.unary_unary(
                '/payment.v1.PaymentService/CalculateWorkerIncome',
                request_serializer=rpc_dot_payment_dot_v1_dot_payment__pb2.CalculateWorkerIncomeRequest.SerializeToString,
                response_deserializer=rpc_dot_payment_dot_v1_dot_payment__pb2.CalculateWorkerIncomeResponse.FromString,
                _registered_method=True)
        self.GetRevenueSummary = channel.unary_unary(
                '/payment.v1.PaymentService/GetRevenueSummary',
                request_serializer=rpc_dot_payment_dot_v1_dot_payment__pb2.GetRevenueSummaryRequest.SerializeToString,
                response_deserializer=rpc_dot_payment_dot_v1_dot_payment__pb2.GetRevenueSummaryResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/payment.v1.PaymentService/Health',
                request_serializer=rpc_dot_payment_dot_v1_dot_payment__pb2.HealthRequest.SerializeToString,
                response_deserializer=rpc_dot_payment_dot_v1_dot_payment__pb2.HealthResponse.FromString,
                _registered_method=True)


class PaymentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPayment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessPaymentCallback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateWorkerIncome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRevenueSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePayment': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePayment,
                    request_deserializer=rpc_dot_payment_dot_v1_dot_payment__pb2.CreatePaymentRequest.FromString,
                    response_serializer=rpc_dot_payment_dot_v1_dot_payment__pb2.CreatePaymentResponse.SerializeToString,
            ),
            'GetPayment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPayment,
                    request_deserializer=rpc_dot_payment_dot_v1_dot_payment__pb2.GetPaymentRequest.FromString,
                    response_serializer=rpc_dot_payment_dot_v1_dot_payment__pb2.GetPaymentResponse.SerializeToString,
            ),
            'ProcessPaymentCallback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessPaymentCallback,
                    request_deserializer=rpc_dot_payment_dot_v1_dot_payment__pb2.ProcessPaymentCallbackRequest.FromString,
                    response_serializer=rpc_dot_payment_dot_v1_dot_payment__pb2.ProcessPaymentCallbackResponse.SerializeToString,
            ),
            'CalculateWorkerIncome': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateWorkerIncome,
                    request_deserializer=rpc_dot_payment_dot_v1_dot_payment__pb2.CalculateWorkerIncomeRequest.FromString,
                    response_serializer=rpc_dot_payment_dot_v1_dot_payment__pb2.CalculateWorkerIncomeResponse.SerializeToString,
            ),
            'GetRevenueSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRevenueSummary,
                    request_deserializer=rpc_dot_payment_dot_v1_dot_payment__pb2.GetRevenueSummaryRequest.FromString,
                    response_serializer=rpc_dot_payment_dot_v1_dot_payment__pb2.GetRevenueSummaryResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=rpc_dot_payment_dot_v1_dot_payment__pb2.HealthRequest.FromString,
                    response_serializer=rpc_dot_payment_dot_v1_dot_payment__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payment.v1.PaymentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payment.v1.PaymentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PaymentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/CreatePayment',
            rpc_dot_payment_dot_v1_dot_payment__pb2.CreatePaymentRequest.SerializeToString,
            rpc_dot_payment_dot_v1_dot_payment__pb2.CreatePaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPayment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/GetPayment',
            rpc_dot_payment_dot_v1_dot_payment__pb2.GetPaymentRequest.SerializeToString,
            rpc_dot_payment_dot_v1_dot_payment__pb2.GetPaymentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessPaymentCallback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/ProcessPaymentCallback',
            rpc_dot_payment_dot_v1_dot_payment__pb2.ProcessPaymentCallbackRequest.SerializeToString,
            rpc_dot_payment_dot_v1_dot_payment__pb2.ProcessPaymentCallbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateWorkerIncome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/CalculateWorkerIncome',
            rpc_dot_payment_dot_v1_dot_payment__pb2.CalculateWorkerIncomeRequest.SerializeToString,
            rpc_dot_payment_dot_v1_dot_payment__pb2.CalculateWorkerIncomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRevenueSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/GetRevenueSummary',
            rpc_dot_payment_dot_v1_dot_payment__pb2.GetRevenueSummaryRequest.SerializeToString,
            rpc_dot_payment_dot_v1_dot_payment__pb2.GetRevenueSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payment.v1.PaymentService/Health',
            rpc_dot_payment_dot_v1_dot_payment__pb2.HealthRequest.SerializeToString,
            rpc_dot_payment_dot_v1_dot_payment__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
